server:
  port: 8080
    
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mvcsecurity
    username: root
    password: india@123
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false

